AWSTemplateFormatVersion: "2010-09-09"
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  Stack for ai deployments

# Global Settings
Globals:
  Function:
    Timeout: 60
    MemorySize: 256

Resources:
  # API Gateway
  AiModelApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: api-v1
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - "*"
        AllowMethods:
          - "*"

  # Lambda Function
  CostOfLivingPredictor:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_handler.lambda_handler
      Runtime: python3.12
      CodeUri: ./cost_of_living_predictor
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: "Allow"
              Resource: "*"
              Action:
                - "dynamodb:*"
      Events:
        CostOfLivingEndpoint:
          Type: HttpApi 
          Properties:
            Path: /bill/predict
            Method: POST
            ApiId: !Ref AiModelApi
  
Outputs:
  EndpointURI:
    Description: "API Endpoint URL"
    Value: !Sub "https://${AiModelApi}.execute-api.${AWS::Region}.amazonaws.com/api-v1"
    Export:
      Name: AiModelApiUrl