AWSTemplateFormatVersion: "2010-09-09"
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  Stack for third party services

Parameters:
  JwtSecretName:
    Type: String
    Description: Name of the secret in Secrets Manager that contains the JWT secret
    Default: python-lambda-app/prod/jwt-secret

  SecretsRegionName:
    Type: String
    Description: Region name where the secrets are stored
    Default: eu-central-1

# Global Settings
Globals:
  Function:
    Timeout: 60
    MemorySize: 256

Resources:
  # API Gateway
  TpsApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: api-v1
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - "*"
        AllowMethods:
          - "*"

  # Lambda Function
  GetAllSuperchargersInACityFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: lambda_handler.lambda_handler
      Runtime: python3.12
      CodeUri: ./
      Environment:
        Variables:
          JWT_SECRET_NAME: !Ref JwtSecretName
          SECRETS_REGION_NAME: !Ref SecretsRegionName
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: "Allow"
              Resource: "*"
              Action:
                - "dynamodb:*"
                - "secretsmanager:GetSecretValue"
      Events:
        GetAllSuperchargersInACityEndpoint:
          Type: HttpApi 
          Properties:
            Path: /superchargers/{city}
            Method: GET
            ApiId: !Ref TpsApi

Outputs:
  EndpointURI:
    Description: "API Endpoint URL"
    Value: !Sub "https://${TpsApi}.execute-api.${AWS::Region}.amazonaws.com/api-v1"
    Export:
      Name: TpsApiUrl