AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  stack for managing regions

# Global Settings
Globals:
  Function:
    Timeout: 60
    MemorySize: 256

Resources:
  # API Gateway
  RegionServiceApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: api-v1
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - "*"
        AllowMethods:
          - "*"

  # DynamoDB Table definition
  RegionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: regions
      AttributeDefinitions:
        - AttributeName: region_name
          AttributeType: S
      KeySchema:
        - AttributeName: region_name
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  # Lambda Functions
  GetAllRegionsWithCitiesFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: ./
      Handler: lambda_handler.lambda_handler
      Runtime: python3.12
      Environment:
        Variables:
          REGIONS_TABLE_NAME: !Ref RegionsTable
      Architectures:
        - x86_64
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - "dynamodb:*"
              Resource: "*"
      Events:
        GetAllRegionsWithCitiesEndpoint:
          Type: HttpApi
          Properties:
            Path: /regions/all
            Method: GET
            ApiId: !Ref RegionServiceApi

Outputs:
  RegionsTableArn:
    Description: "Regions table ARN"
    Value: !GetAtt RegionsTable.Arn
    Export:
      Name: !Sub "${AWS::StackName}-RegionsTableArn"

  RegionsTableName:
    Description: "Regions table NAME"
    Value: !Ref RegionsTable
    Export:
      Name: !Sub "${AWS::StackName}-RegionsTableName"

  EndpointURI:
    Description: "API Endpoint URL"
    Value: !Sub "https://${RegionServiceApi}.execute-api.${AWS::Region}.amazonaws.com/api-v1"
    Export:
      Name: RegionServiceApiUrl
